ushort uShort = 10;
Console.WriteLine(uShort);
short sShort = -11;
Console.WriteLine(sShort);
uint uInt = 12;
Console.WriteLine(uInt);
int sInt = -13;
Console.WriteLine(sInt);
byte uByte = 14;
Console.WriteLine(uByte);
sbyte sByte = -15;
Console.WriteLine(sByte);
ulong uLong = 16;
Console.WriteLine(uLong);
long sLong = -17;
Console.WriteLine(sLong);
char aChar = 'a';
Console.WriteLine(aChar);
string aString = "a string";
Console.WriteLine(aString);
float aFloat = 3.14f;
Console.WriteLine(aFloat);
double aDouble = 6.08;
Console.WriteLine(aDouble);
decimal aDecimal = 999e-2m;
Console.WriteLine(aDecimal);
bool aBoolean = true;
Console.WriteLine(aBoolean);

Console.WriteLine("\r\nNew Values:");
//Modify and reprint the values
uShort = 500;
Console.WriteLine(uShort);
sShort = -0xFE;
Console.WriteLine(sShort);
uInt = 501;
Console.WriteLine(uInt);
sInt = -0b11111111;
Console.WriteLine(sInt);
uByte = 0b10101010;
Console.WriteLine(uByte);
sByte = -0b00000001;
Console.WriteLine(sByte);
uLong = 100000000;
Console.WriteLine(uLong);
sLong = -10000000000;
Console.WriteLine(sLong);
aChar = 'F';
Console.WriteLine(aChar);
aString = "another string";
Console.WriteLine(aString);
aFloat = 12.13f;
Console.WriteLine(aFloat);
aDouble = 14.15;
Console.WriteLine(aDouble);
aDecimal = 100e-2m;
Console.WriteLine(aDecimal);
aBoolean = false;
Console.WriteLine(aBoolean);
